sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t purplewhaling/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true purplewhaling/docker-react npm run test -- --coverage

